// <auto-generated />
using System;
using ApiTest.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiTest.Migrations
{
    [DbContext(typeof(TestingContext))]
    [Migration("20221025192056_testdb1")]
    partial class testdb1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-rc.2.22472.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiTest.Models.Employees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PositionsId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProjectsId")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PositionsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ApiTest.Models.Positions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Testing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ApiTest.Models.Projects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NameProject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ApiTest.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmployeesId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeesId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_fsk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("i_area")
                        .HasColumnType("text");

                    b.Property<string>("i_city")
                        .HasColumnType("text");

                    b.Property<string>("i_index")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("nav_O_Fsks");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_ia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("i_area")
                        .HasColumnType("text");

                    b.Property<string>("i_city")
                        .HasColumnType("text");

                    b.Property<string>("i_index")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("nav_O_Ias");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_mes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("i_area")
                        .HasColumnType("text");

                    b.Property<string>("i_city")
                        .HasColumnType("text");

                    b.Property<string>("i_index")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("nav_O_Mes");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_pmes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("i_area")
                        .HasColumnType("text");

                    b.Property<string>("i_city")
                        .HasColumnType("text");

                    b.Property<string>("i_index")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("nav_O_Pmes");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_substations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("i_area")
                        .HasColumnType("text");

                    b.Property<string>("i_city")
                        .HasColumnType("text");

                    b.Property<string>("i_index")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("nav_O_Substations");
                });

            modelBuilder.Entity("ApiTest.Models.Employees", b =>
                {
                    b.HasOne("ApiTest.Models.Positions", "Positions")
                        .WithMany("Employees")
                        .HasForeignKey("PositionsId");

                    b.HasOne("ApiTest.Models.Projects", "Projects")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectsId");

                    b.Navigation("Positions");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ApiTest.Models.Users", b =>
                {
                    b.HasOne("ApiTest.Models.Employees", "Employees")
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_ia", b =>
                {
                    b.HasOne("ApiTest.Models.nav_o_fsk", "nav_O_Fsk")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("nav_O_Fsk");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_mes", b =>
                {
                    b.HasOne("ApiTest.Models.nav_o_fsk", "nav_O_Fsk")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("nav_O_Fsk");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_pmes", b =>
                {
                    b.HasOne("ApiTest.Models.nav_o_mes", "nav_O_Mes")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("nav_O_Mes");
                });

            modelBuilder.Entity("ApiTest.Models.nav_o_substations", b =>
                {
                    b.HasOne("ApiTest.Models.nav_o_pmes", "nav_O_Pmes")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("nav_O_Pmes");
                });

            modelBuilder.Entity("ApiTest.Models.Positions", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ApiTest.Models.Projects", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
